// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCIdeB0ckq9BGMtbpyRR9QTFe4LJjVIQ0',
    appId: '1:494009922494:web:5ffa39923f4628a564bfef',
    messagingSenderId: '494009922494',
    projectId: 'proyectoramon-599cd',
    authDomain: 'proyectoramon-599cd.firebaseapp.com',
    storageBucket: 'proyectoramon-599cd.firebasestorage.app',
    measurementId: 'G-6DL7708RE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_Hi6Ii4Xiq0l_gEzOuz5gUanT-skKSG0',
    appId: '1:494009922494:android:34460f61292baada64bfef',
    messagingSenderId: '494009922494',
    projectId: 'proyectoramon-599cd',
    storageBucket: 'proyectoramon-599cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaXkqJY07TQwJHF2R5-YQsIkxO4WhZ6mo',
    appId: '1:494009922494:ios:373e8284ae4145ab64bfef',
    messagingSenderId: '494009922494',
    projectId: 'proyectoramon-599cd',
    storageBucket: 'proyectoramon-599cd.firebasestorage.app',
    iosBundleId: 'com.example.copylogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaXkqJY07TQwJHF2R5-YQsIkxO4WhZ6mo',
    appId: '1:494009922494:ios:373e8284ae4145ab64bfef',
    messagingSenderId: '494009922494',
    projectId: 'proyectoramon-599cd',
    storageBucket: 'proyectoramon-599cd.firebasestorage.app',
    iosBundleId: 'com.example.copylogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCIdeB0ckq9BGMtbpyRR9QTFe4LJjVIQ0',
    appId: '1:494009922494:web:6d8fa22007947c0d64bfef',
    messagingSenderId: '494009922494',
    projectId: 'proyectoramon-599cd',
    authDomain: 'proyectoramon-599cd.firebaseapp.com',
    storageBucket: 'proyectoramon-599cd.firebasestorage.app',
    measurementId: 'G-02YS9JD9BL',
  );

}